// <auto-generated />
using System;
using CatanLoggerData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatanLoggerData.Migrations
{
    [DbContext(typeof(CatanLoggerDbContext))]
    [Migration("20230408173846_0.003")]
    partial class _0003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatanLoggerData.Entities.CL_DICEROLL", b =>
                {
                    b.Property<int>("DICE_ROLL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DICE_ROLL_ID"));

                    b.Property<int>("DICE_NUMBER")
                        .HasColumnType("int");

                    b.Property<int>("DICE_ROLLS")
                        .HasColumnType("int");

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.HasKey("DICE_ROLL_ID");

                    b.HasIndex("GAME_ID");

                    b.ToTable("CL_DICEROLL");
                });

            modelBuilder.Entity("CatanLoggerData.Entities.CL_GAME", b =>
                {
                    b.Property<int>("GAME_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GAME_ID"));

                    b.Property<DateTime>("DATE_PLAYED")
                        .HasColumnType("datetime2");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("GAME_ID");

                    b.ToTable("CL_GAME");
                });

            modelBuilder.Entity("CatanLoggerData.Entities.CL_PLAYER", b =>
                {
                    b.Property<int>("PLAYER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PLAYER_ID"));

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.Property<string>("PLAYER_COLOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PLAYER_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TURN_ORDER")
                        .HasColumnType("int");

                    b.Property<bool>("WINNER")
                        .HasColumnType("bit");

                    b.HasKey("PLAYER_ID");

                    b.HasIndex("GAME_ID");

                    b.ToTable("CL_PLAYER");
                });

            modelBuilder.Entity("CatanLoggerData.Entities.CL_DICEROLL", b =>
                {
                    b.HasOne("CatanLoggerData.Entities.CL_GAME", "GAME")
                        .WithMany("DICE_ROLLS")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GAME");
                });

            modelBuilder.Entity("CatanLoggerData.Entities.CL_PLAYER", b =>
                {
                    b.HasOne("CatanLoggerData.Entities.CL_GAME", "GAME")
                        .WithMany("PLAYERS")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GAME");
                });

            modelBuilder.Entity("CatanLoggerData.Entities.CL_GAME", b =>
                {
                    b.Navigation("DICE_ROLLS");

                    b.Navigation("PLAYERS");
                });
#pragma warning restore 612, 618
        }
    }
}
